version: "3.6"
services:
  boilerplate:
    container_name: boilerplate
    restart: always
    build: .
    ports:
      - "8080:8080"
    links:
      - postgres
  postgres:
    container_name: postgres
    image: postgres 
    ports:
      - "5432:5432"